<a href="https://colab.research.google.com/github/dyeee/NLP_Applied-Deep-Learning_202504/blob/main/Recitation_W1_Applied_Deep_Learning_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recitation on Development Infrastructure and PyTorch Tutorial

## Contents
1. Google Colab Basics
2. GPU Environment in Colab
3. Introduction to PyTorch
4. Python Debugging Tools

In [2]:
### 1. Google Colab Basics
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
from pathlib import Path
for path in Path('/content/drive/MyDrive/').glob("*"):
  print(path)

/content/drive/MyDrive/Google Sheets.lnk
/content/drive/MyDrive/Google Slides.lnk
/content/drive/MyDrive/Google Docs.lnk
/content/drive/MyDrive/普物中文版
/content/drive/MyDrive/營服正面
/content/drive/MyDrive/營服背面.png
/content/drive/MyDrive/地科營海報初稿.jpg
/content/drive/MyDrive/營帽.jpg
/content/drive/MyDrive/final地科營海報.jpg
/content/drive/MyDrive/音響社
/content/drive/MyDrive/檔
/content/drive/MyDrive/面試照
/content/drive/MyDrive/傳單.jpg
/content/drive/MyDrive/美影組企劃書.docx
/content/drive/MyDrive/理院演講週
/content/drive/MyDrive/真紅眼黑龍.jpg
/content/drive/MyDrive/Chapter11.ppt
/content/drive/MyDrive/倒數一週.avi
/content/drive/MyDrive/招生片.mp4
/content/drive/MyDrive/羊
/content/drive/MyDrive/A2074.jpg
/content/drive/MyDrive/Project1 (1).exe
/content/drive/MyDrive/Project1.exe
/content/drive/MyDrive/迎新手冊
/content/drive/MyDrive/展覽
/content/drive/MyDrive/總表02.jpg
/content/drive/MyDrive/識別證107108
/content/drive/MyDrive/決賽圖
/content/drive/MyDrive/第六組128至131虌溪野外地質調查.pptx
/content/drive/MyDrive/Mid3
/content/drive/MyDrive/sun

In [5]:
!pip show torch
# !pip install torch

Name: torch
Version: 2.6.0+cu124
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.11/dist-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, fastai, peft, sentence-transformers, timm, torchaudio, torchvision


In [6]:
# Check GPU availability with PyTorch
import torch

print("Is CUDA available?", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0))

# Check GPU details with nvidia-smi
!nvidia-smi

Is CUDA available? True
GPU name: Tesla T4
Mon Apr  7 03:57:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+----

# 1D Array

In [7]:
import torch

# return evenly spaced values within a given interval
range_arr_torch = torch.arange(10)
print("An array given range is \n", range_arr_torch, " with dimensions ", range_arr_torch.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr_torch = torch.linspace(2.0, 3.0, steps=5)
print("An evenly spaced array given range is \n", linspace_arr_torch, " with dimensions ", linspace_arr_torch.shape, "\n")


An array given range is 
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  with dimensions  torch.Size([10]) 

An evenly spaced array given range is 
 tensor([2.0000, 2.2500, 2.5000, 2.7500, 3.0000])  with dimensions  torch.Size([5]) 



In [8]:
# Tensor with uniform distribution between 0 and 1
uniform_tensor = torch.rand(10)
print("Random tensor with elements sampled from a Uniform(0,1) distribution: \n", uniform_tensor, "\n with dimensions ", uniform_tensor.shape, "\n")

Random tensor with elements sampled from a Uniform(0,1) distribution: 
 tensor([0.0013, 0.5462, 0.8952, 0.2750, 0.9150, 0.8390, 0.4403, 0.1462, 0.8710,
        0.4406]) 
 with dimensions  torch.Size([10]) 



In [9]:
# Random tensor with normal distribution (mean=0, std=1)
randn_tensor = torch.randn(10)
print("Random tensor with elements sampled from a N(0,1) distribution: \n", randn_tensor, "\n with dimensions ", randn_tensor.shape, "\n")

Random tensor with elements sampled from a N(0,1) distribution: 
 tensor([ 1.6468, -2.3943, -0.9057, -0.3363,  0.1597,  0.6608,  0.0458,  0.2429,
         0.0838, -0.2157]) 
 with dimensions  torch.Size([10]) 



In [ ]:
# Tensor with all ones
ones_tensor = torch.ones(10)
print("Tensor with all elements set to 1: \n", ones_tensor, "\n with dimensions ", ones_tensor.shape, "\n")

Tensor with all elements set to 1: 
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) 
 with dimensions  torch.Size([10]) 



In [ ]:
# Tensor with all zeros
zeros_tensor = torch.zeros(10)
print("Tensor with all elements set to 0: \n", zeros_tensor, "\n with dimensions ", zeros_tensor.shape, "\n")

Tensor with all elements set to 0: 
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 
 with dimensions  torch.Size([10]) 



In [ ]:
# Tensor from list
list_tensor = torch.tensor([1, 2, 3, 4, 5])
print("Tensor created from a list: \n", list_tensor, "\n with dimensions ", list_tensor.shape, "\n")

Tensor created from a list: 
 tensor([1, 2, 3, 4, 5]) 
 with dimensions  torch.Size([5]) 



In [ ]:
# Cloning a tensor
cloned_tensor = list_tensor.clone()
print("Cloned tensor: \n", cloned_tensor, "\n with dimensions ", cloned_tensor.shape, "\n")

Cloned tensor: 
 tensor([1, 2, 3, 4, 5]) 
 with dimensions  torch.Size([5]) 



In [ ]:
# Tensor with no autograd tracking
with torch.no_grad():
    no_grad_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
print("Tensor with no autograd tracking: \n", no_grad_tensor, "\n with dimensions ", no_grad_tensor.shape, "\n")

Tensor with no autograd tracking: 
 tensor([1., 2., 3.]) 
 with dimensions  torch.Size([3]) 



In [ ]:
# Tensor with requires_grad=True
grad_tensor = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
print("Tensor with requires_grad=True: \n", grad_tensor, "\n with dimensions ", grad_tensor.shape, "\n")

Tensor with requires_grad=True: 
 tensor([1., 2., 3.], requires_grad=True) 
 with dimensions  torch.Size([3]) 



# Multi-Dimensional Tensor

In [ ]:
# Tensor with all zeros (shape: 3x4)
zeros_tensor = torch.zeros(3, 4)
print("Tensor with all elements set to 0: \n", zeros_tensor, "\n with dimensions ", zeros_tensor.shape, "\n")

# Tensor with all ones (shape: 3x4)
ones_tensor = torch.ones(3, 4)
print("Tensor with all elements set to 1: \n", ones_tensor, "\n with dimensions ", ones_tensor.shape, "\n")

# Tensor with all elements set to a specific value, e.g., 7 (shape: 3x4)
full_tensor = torch.full((3, 4), 7)
print("Tensor with all elements set to a specific value (7): \n", full_tensor, "\n with dimensions ", full_tensor.shape, "\n")

# Tensor with random values sampled from a uniform distribution between 0 and 1 (shape: 3x4)
rand_tensor = torch.rand(3, 4)
print("Random tensor with elements sampled from a Uniform(0,1) distribution: \n", rand_tensor, "\n with dimensions ", rand_tensor.shape, "\n")


Tensor with all elements set to 0: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 
 with dimensions  torch.Size([3, 4]) 

Tensor with all elements set to 1: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 
 with dimensions  torch.Size([3, 4]) 

Tensor with all elements set to a specific value (7): 
 tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]) 
 with dimensions  torch.Size([3, 4]) 

Random tensor with elements sampled from a Uniform(0,1) distribution: 
 tensor([[0.4410, 0.8624, 0.9225, 0.9108],
        [0.3641, 0.2494, 0.0717, 0.1293],
        [0.9618, 0.2327, 0.2088, 0.8742]]) 
 with dimensions  torch.Size([3, 4]) 



In [ ]:
# Existing tensor (shape: 300x400)
existing_tensor = torch.rand(300, 400)

# Tensor with all zeros, having the same shape as the existing large tensor
zeros_like_tensor = torch.zeros_like(existing_tensor)
print("Tensor with all elements set to 0, like the existing large tensor: \n", zeros_like_tensor, "\n with dimensions ", zeros_like_tensor.shape, "\n")

# Tensor with all ones, having the same shape as the existing large tensor
ones_like_tensor = torch.ones_like(existing_tensor)
print("Tensor with all elements set to 1, like the existing large tensor: \n", ones_like_tensor, "\n with dimensions ", ones_like_tensor.shape, "\n")

# Tensor with all elements set to a specific value, e.g., 7, having the same shape as the existing large tensor
full_like_tensor = torch.full_like(existing_tensor, 7)
print("Tensor with all elements set to a specific value (7), like the existing large tensor: \n", full_like_tensor, "\n with dimensions ", full_like_tensor.shape, "\n")

Tensor with all elements set to 0, like the existing large tensor: 
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) 
 with dimensions  torch.Size([300, 400]) 

Tensor with all elements set to 1, like the existing large tensor: 
 tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]]) 
 with dimensions  torch.Size([300, 400]) 

Tensor with all elements set to a specific value (7), like the existing large tensor: 
 tensor([[7., 7., 7.,  ..., 7., 7., 7.],
        [7., 7., 7.,  ..., 7., 7., 7.],
        [7., 7., 7.,  ..., 7., 7., 7.],
        ...,
        [7., 7., 7.,  ..., 7., 7., 7.],
     

In [ ]:
import numpy as np

# Create a NumPy ndarray (shape: 3x4)
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Create a PyTorch tensor from the NumPy ndarray
tensor_from_ndarray = torch.tensor(ndarray)
print("Tensor created from a NumPy ndarray: \n", tensor_from_ndarray, "\n with dimensions ", tensor_from_ndarray.shape, "\n")


Tensor created from a NumPy ndarray: 
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
 with dimensions  torch.Size([3, 4]) 



In [ ]:
# Create an example tensor (shape: 3x4)
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Get dimensions of tensor x
print("Size of x: ", x.size(), "\n")

# Concatenate tensors (example: along dimension 0)
tensor_seq = [torch.tensor([13, 14, 15, 16]), torch.tensor([17, 18, 19, 20])]
x_cat = torch.cat(tensor_seq, dim=0)
print("Concatenated tensor x_cat: \n", x_cat, "\n with dimensions ", x_cat.shape, "\n")

# Reshape tensor
y_reshape = x.view(2, 6)
print("Reshaped tensor y: \n", y_reshape, "\n with dimensions ", y_reshape.shape, "\n")

# Reshape with inferred dimension
y_infer = x.view(-1, 6)
print("Reshaped tensor with inferred dimension y: \n", y_infer, "\n with dimensions ", y_infer.shape, "\n")

# Transpose tensor
y_transpose = x.transpose(0, 1)
print("Transposed tensor y: \n", y_transpose, "\n with dimensions ", y_transpose.shape, "\n")

# Permute dimensions
y_permute = x.permute(1, 0)
print("Permuted tensor y: \n", y_permute, "\n with dimensions ", y_permute.shape, "\n")

# Add dimension
y_unsqueeze = x.unsqueeze(dim=0)
print("Unsqueezed tensor y: \n", y_unsqueeze, "\n with dimensions ", y_unsqueeze.shape, "\n")

# Add dimension at specified index
y_unsqueeze_specific = x.unsqueeze(dim=2)
print("Specifically unsqueezed tensor y: \n", y_unsqueeze_specific, "\n with dimensions ", y_unsqueeze_specific.shape, "\n")

# Remove dimensions of size 1
y_squeeze = y_unsqueeze_specific.squeeze()
print("Squeezed tensor y: \n", y_squeeze, "\n with dimensions ", y_squeeze.shape, "\n")

# Remove specified dimensions of size 1
y_squeeze_specific = y_unsqueeze_specific.squeeze(dim=2)
print("Specifically squeezed tensor y: \n", y_squeeze_specific, "\n with dimensions ", y_squeeze_specific.shape, "\n")

Size of x:  torch.Size([3, 4]) 

Concatenated tensor x_cat: 
 tensor([13, 14, 15, 16, 17, 18, 19, 20]) 
 with dimensions  torch.Size([8]) 

Reshaped tensor y: 
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]) 
 with dimensions  torch.Size([2, 6]) 

Reshaped tensor with inferred dimension y: 
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]) 
 with dimensions  torch.Size([2, 6]) 

Transposed tensor y: 
 tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]]) 
 with dimensions  torch.Size([4, 3]) 

Permuted tensor y: 
 tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]]) 
 with dimensions  torch.Size([4, 3]) 

Unsqueezed tensor y: 
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]) 
 with dimensions  torch.Size([1, 3, 4]) 

Specifically unsqueezed tensor y: 
 tensor([[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6

In [ ]:
# Create a 3D tensor (shape: 2x3x4)
x_3d = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

# Get dimensions of 3D tensor x_3d
print("Size of x_3d: ", x_3d.size(), "\n")

# Transpose 3D tensor (swap dimensions 0 and 1)
y_transpose_3d = x_3d.transpose(0, 1)
print("Transposed 3D tensor y: \n", y_transpose_3d, "\n with dimensions ", y_transpose_3d.shape, "\n")

# Permute dimensions of 3D tensor (new order: 1, 0, 2)
y_permute_3d = x_3d.permute(1, 0, 2)
print("Permuted 3D tensor y: \n", y_permute_3d, "\n with dimensions ", y_permute_3d.shape, "\n")

Size of x_3d:  torch.Size([2, 3, 4]) 

Transposed 3D tensor y: 
 tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]]) 
 with dimensions  torch.Size([3, 2, 4]) 

Permuted 3D tensor y: 
 tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]]) 
 with dimensions  torch.Size([3, 2, 4]) 



# Debugging in Python
* Syntax Error -> ChatGPT
* Runtime Error -> IPython pdb (ipdb)
* Tensor Error -> ipdb
* GPU-related Error -> Next Recitation

In [ ]:
!pip install ipdb
import ipdb

# 常用的 ipdb 指令解釋：

- `n`（next）：繼續執行，直到達到當前函數中的下一行，或者它返回。
- `c`（continue）：繼續執行，僅在遇到斷點時停止。
- `q`（quit）：退出調試器和程序。
- `p`（print）：評估並列印表達式。
- `l`（list）：列出當前文件的源代碼。
- `s`（step）：執行當前行，並在第一個可能的場合停止（例如，在一個函數呼叫中）。

使用 `ipdb` 的方法有多種，以下是一些常見的使用案例：

1. **啟動調試模式**：直接在命令行中輸入以下指令來啟動 `ipdb` 調試模式。
    ```bash
    python -m ipdb your_script.py
    ```
    這會在腳本的開始處暫停執行，允許你逐步執行代碼。

2. **自動繼續執行**：如果你只想在設置了斷點（breakpoint）的地方暫停，則可以使用以下指令：
    ```bash
    python -m ipdb -c continue your_script.py
    ```
    使用 `-c continue` 會讓腳本在啟動後自動繼續執行，直到達到第一個斷點或是報錯點。

3. **指定執行參數**：如果你的腳本需要傳入參數，可以這麼做：
    ```bash
    python -m ipdb your_script.py --your-arg value
    ```
    只需正常地將參數放在腳本名稱後面即可

4. **使用條件斷點**：在你的腳本中，你可以添加 `ipdb.set_trace()` 方法來設置斷點。要讓斷點有條件地觸發，可以這樣使用：
    ```python
    if some_condition:
        ipdb.set_trace()
    ```
5. **例外時自動觸發調試**：如果你希望只在出現未捕獲的例外（exception）時啟動 `ipdb`，可以使用 `ipdb.launch_ipdb_on_exception()` 上下文管理器。這在嘗試調試偶爾出錯的代碼時特別有用。
    ```python
    with ipdb.launch_ipdb_on_exception():
        main()
        # 其他可能出錯的代碼...
    ```
    當 `main()` 函數或其他代碼塊拋出未捕獲的例外時，`ipdb` 會自動啟動，允許你立即檢查問題。

這些是在命令行中使用 `ipdb` 的一些基本方法，有助於更有效地進行代碼調試。    

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# 生成假資料
n_samples = 1000
X = torch.rand(n_samples, 10)
y = 3 * X.sum(dim=1) + 2 + torch.randn(n_samples)  # y = 3x + 2 + noise

# 建立資料集和資料載入器
dataset = TensorDataset(X, y)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# 定義一個簡單的 MLP 模型
class SimpleMLP(nn.Module):
    def __init__(self):
        super(SimpleMLP, self).__init__()
        self.fc1 = nn.Linear(10, 5)
        self.fc2 = nn.Linear(5, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [ ]:
# 初始化模型、損失函數和優化器
model = SimpleMLP()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 訓練模型
for epoch in range(10):
    for batch_X, batch_y in dataloader:
        # 前向傳播
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)

        # 反向傳播和優化
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch [{epoch+1}/10], Loss: {loss.item():.4f}")

print("Training complete.")

NameError: ignored

In [ ]:
print(f"Model is on: {next(model.parameters()).device}")

Model is on: cpu


In [ ]:
!nvidia-smi
device = torch.device("cuda:0")

Mon Sep  4 11:01:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     8W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------